[package]
name        = "corex"
version     = { workspace = true }
edition     = { workspace = true }
description = "Corex CLI — run shortcuts, manage daemon, inspect actions"
authors     = { workspace = true }
license     = { workspace = true }

[[bin]]
name = "corex"
path = "src/main.rs"

[dependencies]
corex-core     = { workspace = true }
corex-engine   = { workspace = true }
corex-registry = { workspace = true }
corex-ipc      = { workspace = true }
anyhow         = { workspace = true }
clap           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
serde_yml      = { workspace = true }
tokio          = { workspace = true }
toml           = { workspace = true }
tracing        = { workspace = true }
tracing-subscriber = { workspace = true }
